name: Update EPG
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  grab:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Extra layer of permission security
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Grab EPG
        run: npm run grab -- --channels=./custom.channels.xml --output=guide.xml

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add guide.xml
          git commit -m "Update guide.xml" || echo "No changes to commit"
          git push origin main
